# Generated by Django 3.1.7 on 2021-03-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=264, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('up_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_key', models.CharField(max_length=264)),
                ('value', models.CharField(max_length=264)),
                ('up_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_property',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(unique=True)),
                ('link', models.CharField(default='no_link', max_length=264)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomProperty',
            fields=[
                ('rp_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('room_key', models.CharField(max_length=264)),
                ('value', models.CharField(max_length=264)),
                ('rp_rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rooms')),
            ],
            options={
                'db_table': 'room_property',
            },
        ),
    ]
