# Generated by Django 3.1.7 on 2021-02-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('up_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_key', models.CharField(max_length=264)),
                ('value', models.CharField(max_length=264)),
                ('up_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_property',
            },
        ),
    ]
